"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
scan_timeout = 10
command_timeout = 500
palette = 'catppuccin_mocha'
format = '$directory$git_branch$git_status$fill$cmd_duration$python$username$hostname$line_break$character'

[palettes.catppuccin_mocha]
blue = '#89b4fa'
grey = '#a6adc8'
yellow = '#f9e2af'
magenta = '#cba6f7'
red = '#f38ba8'
white = '#cdd6f4'

[directory]
style = 'blue'
truncation_length = 0
truncate_to_repo = false
format = '[$path]($style) '

[git_branch]
symbol = ''
style = 'grey'
format = '[$branch]($style) '

[git_status]
style = 'grey'
format = '([$all_status$ahead_behind]($style) )'
conflicted = '='
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
untracked = '*'
stashed = '≡'
modified = '!'
staged = '+'
renamed = '»'
deleted = '✘'

[cmd_duration]
min_time = 5_000
style = 'yellow'
format = '[$duration]($style) '

[python]
style = 'grey'
format = '[($virtualenv )]($style)'

[username]
show_always = false
style_user = 'grey'
format = '[$user]($style)'

[hostname]
ssh_only = true
style = 'grey'
format = '[@$hostname]($style) '

[character]
success_symbol = '[❯](magenta)'
error_symbol = '[❯](red)'
vimcmd_symbol = '[❮](magenta)'
